services:
  - type: web
    name: trudesk
    runtime: node
    region: ohio
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: PORT=$PORT yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8118
      - key: TRUDESK_DOCKER
        value: "true"
      - key: TRUDESK_JWTSECRET
        generateValue: true
      - key: TD_MONGODB_URL
        value: mongodb://${trudesk-mongodb.username}:${trudesk-mongodb.password}@${trudesk-mongodb.host}:${trudesk-mongodb.port}/${trudesk-mongodb.database}
      - key: REDIS_URL
        value: ${trudesk-redis.REDIS_URL}
      - key: ELASTICSEARCH_URI
        value: ""
      - key: NODE_VERSION
        value: 16.20.0

  - type: redis
    name: trudesk-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: trudesk-mongodb
    databaseName: trudesk
    plan: free
