services:
  - type: web
    name: trudesk
    runtime: node
    region: oregon
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: PORT=10000 yarn start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TRUDESK_DOCKER
        value: "true"
      - key: TRUDESK_JWTSECRET
        generateValue: true
      - key: TD_MONGODB_URL
        value: mongodb://trudesk-mongodb:27017/trudesk
      - key: REDIS_URL
        value: ${trudesk-redis.REDIS_URL}
      - key: ELASTICSEARCH_URI
        value: ""
      - key: NODE_VERSION
        value: 16.20.0

  - type: redis
    name: trudesk-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

  - type: pserv
    name: trudesk-mongodb
    runtime: docker
    region: oregon
    plan: free
    image:
      url: mongo:4.4
    envVars:
      - key: MONGO_INITDB_DATABASE
        value: trudesk
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 10
